"""Canonical Sherpa WebSocket event vocabulary shared across the platform."""

SHERPA_RECOMMENDATIONS = "sherpa_recommendations"
SHERPA_DECISION_ACK = "sherpa_decision_ack"
SHERPA_CHAT_START = "sherpa_chat_start"
SHERPA_CHAT_CHUNK = "sherpa_chat_chunk"
SHERPA_CHAT_DONE = "sherpa_chat_done"
SHERPA_STATUS = "sherpa_status"
SHERPA_PEAKS_RESULT = "sherpa_peaks_result"
SHERPA_PEAKS_ERROR = "sherpa_peaks_error"
SHERPA_CODE_RESULT = "sherpa_code_result"
SHERPA_CODE_ERROR = "sherpa_code_error"
SHERPA_TOOL_START = "sherpa_tool_start"
SHERPA_TOOL_RESULT = "sherpa_tool_result"
SHERPA_SUBSCRIPTION_REQUIRED = "sherpa_subscription_required"
SHERPA_ERROR = "sherpa_error"
SHERPA_REPORT_RESULT = "sherpa_report_result"
SHERPA_REPORT_ERROR = "sherpa_report_error"
SHERPA_DATA_STORY_RESULT = "sherpa_data_story_result"
SHERPA_DATA_STORY_ERROR = "sherpa_data_story_error"
