"""Add DOE configuration profiles table

Revision ID: 159e3481af1b
Revises: e9472434d5ee
Create Date: 2026-01-04 15:25:37.128536

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "159e3481af1b"
down_revision = "e9472434d5ee"
branch_labels = None
depends_on = None


def _table_exists(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    indexes = sa.inspect(op.get_bind()).get_indexes(table_name)
    return any(idx["name"] == index_name for idx in indexes)


def upgrade() -> None:
    if not _table_exists("doe_config"):
        op.create_table(
            "doe_config",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("is_default", sa.Boolean(), nullable=False),
            sa.Column("folder_batch_rules", sa.JSON(), nullable=True),
            sa.Column("filename_patterns", sa.JSON(), nullable=True),
            sa.Column("scan_defaults", sa.JSON(), nullable=True),
            sa.Column("run_sequence_template", sa.JSON(), nullable=True),
            sa.Column("match_settings", sa.JSON(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _index_exists("doe_config", op.f("ix_doe_config_user_id")):
        op.create_index(
            op.f("ix_doe_config_user_id"),
            "doe_config",
            ["user_id"],
            unique=False,
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_doe_config_user_id"), table_name="doe_config")
    op.drop_table("doe_config")
    # ### end Alembic commands ###
