"""remove_custom_algo_table

Revision ID: a76d82a816bf
Revises: o5j7k9l1m704
Create Date: 2026-03-09 01:36:08.757019

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a76d82a816bf"
down_revision = "o5j7k9l1m704"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_custom_algo_project_id"), table_name="custom_algo")
    op.drop_index(op.f("ix_custom_algo_user_id"), table_name="custom_algo")
    op.drop_table("custom_algo")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "custom_algo",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("project_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("code", sa.TEXT(), nullable=False),
        sa.Column("mode", sa.VARCHAR(length=20), server_default=sa.text("'simple'"), nullable=False),
        sa.Column("icon", sa.VARCHAR(length=10), server_default=sa.text("'🧪'"), nullable=False),
        sa.Column("node_type", sa.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_type"),
    )
    op.create_index(op.f("ix_custom_algo_user_id"), "custom_algo", ["user_id"], unique=False)
    op.create_index(op.f("ix_custom_algo_project_id"), "custom_algo", ["project_id"], unique=False)
    # ### end Alembic commands ###
