"""remove_custom_algo_table

Revision ID: a76d82a816bf
Revises: o5j7k9l1m704
Create Date: 2026-03-09 01:36:08.757019

Custom algos were replaced by project-scoped loader plugins.
This migration drops the legacy ``custom_algo`` table.  Any rows
present are logged as a WARNING before the drop so operators can
take a manual backup if needed.
"""

from __future__ import annotations

import logging

import sqlalchemy as sa
from alembic import op

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision = "a76d82a816bf"
down_revision = "o5j7k9l1m704"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # Warn if the table has data so operators can back it up before the drop.
    try:
        result = conn.execute(sa.text("SELECT COUNT(*) FROM custom_algo"))
        row_count = result.scalar() or 0
        if row_count > 0:
            logger.warning(
                "Dropping 'custom_algo' table which still contains %d row(s). "
                "Custom algos have been superseded by project-scoped loader plugins. "
                "Back up this data manually if you need to preserve it.",
                row_count,
            )
    except Exception:
        pass  # Table may already be absent on a fresh DB — safe to continue.

    op.drop_index(op.f("ix_custom_algo_project_id"), table_name="custom_algo")
    op.drop_index(op.f("ix_custom_algo_user_id"), table_name="custom_algo")
    op.drop_table("custom_algo")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "custom_algo",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("project_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=255), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("code", sa.TEXT(), nullable=False),
        sa.Column("mode", sa.VARCHAR(length=20), server_default=sa.text("'simple'"), nullable=False),
        sa.Column("icon", sa.VARCHAR(length=10), server_default=sa.text("'🧪'"), nullable=False),
        sa.Column("node_type", sa.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_type"),
    )
    op.create_index(op.f("ix_custom_algo_user_id"), "custom_algo", ["user_id"], unique=False)
    op.create_index(op.f("ix_custom_algo_project_id"), "custom_algo", ["project_id"], unique=False)
    # ### end Alembic commands ###
