"""Add workflow annotations

Revision ID: d0f6e1b4cf70
Revises: c9e5f0a3de6f
Create Date: 2026-01-15 12:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f6e1b4cf70'
down_revision = 'c9e5f0a3de6f'
branch_labels = None
depends_on = None


def _table_exists(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _column_exists(table_name: str, column_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    columns = sa.inspect(op.get_bind()).get_columns(table_name)
    return any(col["name"] == column_name for col in columns)


def upgrade() -> None:
    if _table_exists("workflow") and not _column_exists("workflow", "notes"):
        op.add_column("workflow", sa.Column("notes", sa.Text(), nullable=True))

    if _table_exists("workflow_node") and not _column_exists("workflow_node", "annotation"):
        op.add_column("workflow_node", sa.Column("annotation", sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_node', 'annotation')
    op.drop_column('workflow', 'notes')
    # ### end Alembic commands ###
