"""Add factor_values JSON field to matched_acquisition

Revision ID: e9472434d5ee
Revises: 4724968e5531
Create Date: 2026-01-04 15:17:15.319425

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9472434d5ee'
down_revision = '4724968e5531'
branch_labels = None
depends_on = None


def _table_exists(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _column_exists(table_name: str, column_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    columns = sa.inspect(op.get_bind()).get_columns(table_name)
    return any(col["name"] == column_name for col in columns)


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    indexes = sa.inspect(op.get_bind()).get_indexes(table_name)
    return any(idx["name"] == index_name for idx in indexes)


def upgrade() -> None:
    # Backward-compat bootstrap for fresh DBs that do not have this legacy table yet.
    if not _table_exists("matched_acquisition"):
        op.create_table(
            "matched_acquisition",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("experiment_id", sa.Integer(), nullable=False),
            sa.Column("seq", sa.Integer(), nullable=True),
            sa.Column("filename", sa.String(length=255), nullable=True),
            sa.Column("folder", sa.String(length=255), nullable=True),
            sa.Column("timestamp", sa.Integer(), nullable=True),
            sa.Column("date", sa.String(length=50), nullable=True),
            sa.Column("batch", sa.Integer(), nullable=True),
            sa.Column("sample_id", sa.String(length=100), nullable=True),
            sa.Column("cell", sa.String(length=50), nullable=True),
            sa.Column("special", sa.String(length=100), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
    if not _index_exists("matched_acquisition", "ix_matched_acquisition_experiment_id"):
        op.create_index(
            "ix_matched_acquisition_experiment_id",
            "matched_acquisition",
            ["experiment_id"],
            unique=False,
        )
    if not _column_exists("matched_acquisition", "factor_values"):
        op.add_column(
            "matched_acquisition",
            sa.Column("factor_values", sa.JSON(), nullable=True),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matched_acquisition', 'factor_values')
    # ### end Alembic commands ###
