"""Add data egress permissions tables

Revision ID: f1a7b2c5de8f
Revises: d0f6e1b4cf70
Create Date: 2026-02-05 10:00:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a7b2c5de8f'
down_revision = 'd0f6e1b4cf70'
branch_labels = None
depends_on = None


def _table_exists(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    indexes = sa.inspect(op.get_bind()).get_indexes(table_name)
    return any(idx["name"] == index_name for idx in indexes)


def upgrade() -> None:
    if not _table_exists("user_egress_defaults"):
        op.create_table(
            "user_egress_defaults",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column(
                "allow_spectrasherpa_sync",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            ),
            sa.Column(
                "allow_llm_context",
                sa.Boolean(),
                nullable=False,
                server_default="1",
            ),
            sa.Column("allow_export", sa.Boolean(), nullable=False, server_default="1"),
            sa.Column(
                "allow_nist_queries",
                sa.Boolean(),
                nullable=False,
                server_default="1",
            ),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("user_id"),
        )

    if not _table_exists("data_egress_permissions"):
        op.create_table(
            "data_egress_permissions",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("data_type", sa.String(length=50), nullable=False),
            sa.Column("destination", sa.String(length=50), nullable=False),
            sa.Column("allowed", sa.Boolean(), nullable=False, server_default="1"),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "user_id",
                "data_type",
                "destination",
                name="uq_user_datatype_destination",
            ),
        )
    if not _index_exists("data_egress_permissions", op.f("ix_data_egress_permissions_user_id")):
        op.create_index(
            op.f("ix_data_egress_permissions_user_id"),
            "data_egress_permissions",
            ["user_id"],
            unique=False,
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_egress_permissions_user_id'), table_name='data_egress_permissions')
    op.drop_table('data_egress_permissions')
    op.drop_table('user_egress_defaults')
    # ### end Alembic commands ###
