/**
 * Auto-generated TypeScript types from OpenAPI schema.
 *
 * To regenerate, start the backend server and run:
 *   npm run generate:types
 *
 * Do not edit this file manually.
 */

// Run `npm run generate:types` with the backend running to populate this file.
export {};
