"""
Seed data for common workflow templates.

This module defines pre-built workflow templates for common chemometrics tasks.
"""

WORKFLOW_TEMPLATES = [
    {
        "name": "PCA Exploratory Analysis",
        "description": (
            "Load spectral data, apply preprocessing, and perform PCA for exploratory"
            " data analysis. Visualize scores and loadings to identify patterns and outliers."
        ),
        "category": "exploratory",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pca",
                    "label": "PCA",
                    "parameters": {"n_components": 5},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.scatter_plot",
                    "label": "Scores Plot",
                    "parameters": {"pc_x": 1, "pc_y": 2},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "viz_2",
                    "node_type": "output.line_plot",
                    "label": "Loadings Plot",
                    "parameters": {"components": [1, 2]},
                    "position_x": 700,
                    "position_y": 250,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_2"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "PLSRegression Calibration",
        "description": (
            "Build a PLS regression model for quantitative calibration. Includes"
            " preprocessing, PLS modeling, cross-validation, and prediction visualization."
        ),
        "category": "calibration",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Calibration Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.savgol",
                    "label": "Savitzky-Golay",
                    "parameters": {"window_length": 15, "polyorder": 2, "deriv": 1},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pls_regression",
                    "label": "PLS Regression",
                    "parameters": {"n_components": 3},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "eval_1",
                    "node_type": "evaluation.cross_validation",
                    "label": "Cross-Validation",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.scatter_plot",
                    "label": "Predicted vs Actual",
                    "parameters": {},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "eval_1"},
                {"from_node_id": "eval_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Classification (PCA + LDA)",
        "description": (
            "Supervised classification workflow using PCA for dimensionality reduction"
            " followed by LDA for class discrimination."
        ),
        "category": "classification",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.baseline",
                    "label": "Baseline Correction",
                    "parameters": {"method": "als"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pca",
                    "label": "PCA",
                    "parameters": {"n_components": 10},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "model_2",
                    "node_type": "model.lda",
                    "label": "LDA",
                    "parameters": {},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.scatter_plot",
                    "label": "LDA Scores",
                    "parameters": {},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "model_2"},
                {"from_node_id": "model_2", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "MCR-ALS Curve Resolution",
        "description": (
            "Multivariate Curve Resolution - Alternating Least Squares for resolving"
            " overlapping spectral components."
        ),
        "category": "curve_resolution",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.efa",
                    "label": "EFA",
                    "parameters": {"n_components": 3},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_2",
                    "node_type": "model.mcr_als",
                    "label": "MCR-ALS",
                    "parameters": {"n_components": 3, "max_iter": 50, "tol": 0.1},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.line_plot",
                    "label": "Resolved Spectra",
                    "parameters": {},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "viz_2",
                    "node_type": "output.line_plot",
                    "label": "Concentrations",
                    "parameters": {},
                    "position_x": 700,
                    "position_y": 250,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "model_2"},
                {"from_node_id": "model_2", "to_node_id": "viz_1"},
                {"from_node_id": "model_2", "to_node_id": "viz_2"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Preprocessing Pipeline",
        "description": (
            "Comprehensive spectral preprocessing workflow: baseline correction,"
            " smoothing, normalization, and derivative."
        ),
        "category": "preprocessing",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Raw Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.baseline",
                    "label": "Baseline Correction",
                    "parameters": {"method": "als"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_2",
                    "node_type": "preprocessing.savgol",
                    "label": "Smoothing",
                    "parameters": {"window_length": 11, "polyorder": 2, "deriv": 0},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_3",
                    "node_type": "preprocessing.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.spectra",
                    "label": "View Spectra",
                    "parameters": {},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "preprocess_2"},
                {"from_node_id": "preprocess_2", "to_node_id": "preprocess_3"},
                {"from_node_id": "preprocess_3", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Quality Control (SIMCA)",
        "description": "Build a SIMCA model for quality control and outlier detection based on reference class.",
        "category": "quality_control",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Reference Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.simca",
                    "label": "SIMCA",
                    "parameters": {"n_components": 5, "alpha": 0.05},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.scatter_plot",
                    "label": "Coomans Plot",
                    "parameters": {},
                    "position_x": 700,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Hierarchical Clustering",
        "description": "Unsupervised clustering workflow using hierarchical clustering to group similar spectra.",
        "category": "clustering",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.hierarchical_clustering",
                    "label": "Hierarchical Clustering",
                    "parameters": {"n_clusters": 3, "linkage": "ward"},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.dendrogram",
                    "label": "Dendrogram",
                    "parameters": {},
                    "position_x": 700,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "KNN Classification",
        "description": "K-Nearest Neighbors classification for supervised learning with cross-validation.",
        "category": "classification",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Training Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.savgol",
                    "label": "Savitzky-Golay",
                    "parameters": {"window_length": 15, "polyorder": 2, "deriv": 1},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.knn",
                    "label": "KNN Classifier",
                    "parameters": {"n_neighbors": 5, "metric": "euclidean"},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "eval_1",
                    "node_type": "evaluation.cross_validation",
                    "label": "Cross-Validation",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.data_table",
                    "label": "Classification Report",
                    "parameters": {},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "eval_1"},
                {"from_node_id": "eval_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Variable Selection + PLS",
        "description": "Feature selection followed by PLS regression for improved calibration performance.",
        "category": "calibration",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "feature_1",
                    "node_type": "preprocessing.variable_selection",
                    "label": "Variable Selection",
                    "parameters": {"method": "variance", "threshold": 0.01},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pls_regression",
                    "label": "PLS Regression",
                    "parameters": {"n_components": 5},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.scatter_plot",
                    "label": "Predictions",
                    "parameters": {},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "feature_1"},
                {"from_node_id": "feature_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Compare Multiple Models",
        "description": (
            "Compare different classification models (KNN, LDA, SVM) on the same" " dataset with cross-validation."
        ),
        "category": "comparison",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.load_experiment",
                    "label": "Load Data",
                    "parameters": {},
                    "position_x": 100,
                    "position_y": 250,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocessing.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 250,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.knn",
                    "label": "KNN",
                    "parameters": {"n_neighbors": 5},
                    "position_x": 500,
                    "position_y": 150,
                },
                {
                    "node_id": "model_2",
                    "node_type": "model.lda",
                    "label": "LDA",
                    "parameters": {},
                    "position_x": 500,
                    "position_y": 250,
                },
                {
                    "node_id": "model_3",
                    "node_type": "model.svm",
                    "label": "SVM",
                    "parameters": {"kernel": "rbf"},
                    "position_x": 500,
                    "position_y": 350,
                },
                {
                    "node_id": "eval_1",
                    "node_type": "evaluation.cross_validation",
                    "label": "CV - KNN",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "eval_2",
                    "node_type": "evaluation.cross_validation",
                    "label": "CV - LDA",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 250,
                },
                {
                    "node_id": "eval_3",
                    "node_type": "evaluation.cross_validation",
                    "label": "CV - SVM",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 350,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_2"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_3"},
                {"from_node_id": "model_1", "to_node_id": "eval_1"},
                {"from_node_id": "model_2", "to_node_id": "eval_2"},
                {"from_node_id": "model_3", "to_node_id": "eval_3"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
]
