"""
Seed data for common workflow templates.

This module defines pre-built workflow templates for common chemometrics tasks.
All node types and parameter names match the registered node library exactly.
"""

WORKFLOW_TEMPLATES = [
    {
        "name": "PCA Exploratory Analysis",
        "description": (
            "Load spectral data, apply preprocessing, and perform PCA for exploratory"
            " data analysis. Visualize scores and loadings to identify patterns and outliers."
        ),
        "category": "exploratory",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocess.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pca",
                    "label": "PCA",
                    "parameters": {"n_components": "5"},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "Scores Plot",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "viz_2",
                    "node_type": "output.plot",
                    "label": "Loadings Plot",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 700,
                    "position_y": 250,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_2"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "PLSRegression Calibration",
        "description": (
            "Build a PLS regression model for quantitative calibration. Includes"
            " preprocessing, PLS modeling, cross-validation, and prediction visualization."
        ),
        "category": "calibration",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Calibration Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocess.smooth",
                    "label": "Savitzky-Golay",
                    "parameters": {"method": "savitzky_golay", "size": 15, "order": 2},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pls",
                    "label": "PLS Regression",
                    "parameters": {"n_components": 3},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "eval_1",
                    "node_type": "diagnostics.cross_validation",
                    "label": "Cross-Validation",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "Predicted vs Actual",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "eval_1"},
                {"from_node_id": "eval_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Classification (PCA + PLS-DA)",
        "description": (
            "Supervised classification workflow using PCA for dimensionality reduction"
            " followed by PLS-DA for class discrimination."
        ),
        "category": "classification",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "baseline.penalized_ls",
                    "label": "Baseline Correction",
                    "parameters": {"method": "als", "lam": 100000, "p": 0.001},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pca",
                    "label": "PCA",
                    "parameters": {"n_components": "10"},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "model_2",
                    "node_type": "classification.plsda",
                    "label": "PLS-DA",
                    "parameters": {"n_components": 2},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "Classification Scores",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "model_2"},
                {"from_node_id": "model_2", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "MCR-ALS Curve Resolution",
        "description": (
            "Multivariate Curve Resolution - Alternating Least Squares for resolving"
            " overlapping spectral components."
        ),
        "category": "curve_resolution",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.efa",
                    "label": "EFA",
                    "parameters": {"n_components": 3},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_2",
                    "node_type": "model.mcr_als",
                    "label": "MCR-ALS",
                    "parameters": {"n_components": 3, "max_iter": 50, "tol": 0.1},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "Resolved Spectra",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "viz_2",
                    "node_type": "output.plot",
                    "label": "Concentrations",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 700,
                    "position_y": 250,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "model_2"},
                {"from_node_id": "model_2", "to_node_id": "viz_1"},
                {"from_node_id": "model_2", "to_node_id": "viz_2"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Preprocessing Pipeline",
        "description": (
            "Comprehensive spectral preprocessing workflow: baseline correction,"
            " smoothing, normalization, and visualization."
        ),
        "category": "preprocessing",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Raw Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "baseline.penalized_ls",
                    "label": "Baseline Correction",
                    "parameters": {"method": "als", "lam": 100000, "p": 0.001},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_2",
                    "node_type": "preprocess.smooth",
                    "label": "Smoothing",
                    "parameters": {"method": "savitzky_golay", "size": 11, "order": 2},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_3",
                    "node_type": "preprocess.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "View Spectra",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "preprocess_2"},
                {"from_node_id": "preprocess_2", "to_node_id": "preprocess_3"},
                {"from_node_id": "preprocess_3", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Quality Control (SIMCA)",
        "description": "Build a SIMCA model for quality control and outlier detection based on reference class.",
        "category": "quality_control",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Reference Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocess.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "classification.simca",
                    "label": "SIMCA",
                    "parameters": {"n_components": 3, "confidence_level": 0.95},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "Coomans Plot",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 700,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Hierarchical Clustering",
        "description": "Unsupervised clustering workflow using hierarchical clustering to group similar spectra.",
        "category": "clustering",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocess.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.hca",
                    "label": "Hierarchical Clustering",
                    "parameters": {"n_clusters": 3, "linkage": "ward"},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "Dendrogram",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 700,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "KNN Classification",
        "description": "K-Nearest Neighbors classification for supervised learning with cross-validation.",
        "category": "classification",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Training Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocess.smooth",
                    "label": "Savitzky-Golay",
                    "parameters": {"method": "savitzky_golay", "size": 15, "order": 2},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "classification.knn",
                    "label": "KNN Classifier",
                    "parameters": {"n_neighbors": 5, "metric": "euclidean"},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "eval_1",
                    "node_type": "diagnostics.cross_validation",
                    "label": "Cross-Validation",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.data_table",
                    "label": "Classification Report",
                    "parameters": {},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "eval_1"},
                {"from_node_id": "eval_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Spectral Region Selection + PLS",
        "description": "Spectral region selection followed by PLS regression for targeted calibration.",
        "category": "calibration",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 200,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocess.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 200,
                },
                {
                    "node_id": "feature_1",
                    "node_type": "preprocess.clip_range",
                    "label": "Region Selection",
                    "parameters": {"min_wavenumber": 400, "max_wavenumber": 4000},
                    "position_x": 500,
                    "position_y": 200,
                },
                {
                    "node_id": "model_1",
                    "node_type": "model.pls",
                    "label": "PLS Regression",
                    "parameters": {"n_components": 5},
                    "position_x": 700,
                    "position_y": 200,
                },
                {
                    "node_id": "viz_1",
                    "node_type": "output.plot",
                    "label": "Predictions",
                    "parameters": {"plot_type": "spectra"},
                    "position_x": 900,
                    "position_y": 200,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "feature_1"},
                {"from_node_id": "feature_1", "to_node_id": "model_1"},
                {"from_node_id": "model_1", "to_node_id": "viz_1"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
    {
        "name": "Compare Multiple Classifiers",
        "description": (
            "Compare different classification models (KNN, PLS-DA, SIMCA) on the same" " dataset with cross-validation."
        ),
        "category": "comparison",
        "template_data": {
            "nodes": [
                {
                    "node_id": "data_1",
                    "node_type": "data.source",
                    "label": "Load Data",
                    "parameters": {"source": "experiment"},
                    "position_x": 100,
                    "position_y": 250,
                },
                {
                    "node_id": "preprocess_1",
                    "node_type": "preprocess.normalize",
                    "label": "Normalize",
                    "parameters": {"method": "snv"},
                    "position_x": 300,
                    "position_y": 250,
                },
                {
                    "node_id": "model_1",
                    "node_type": "classification.knn",
                    "label": "KNN",
                    "parameters": {"n_neighbors": 5},
                    "position_x": 500,
                    "position_y": 150,
                },
                {
                    "node_id": "model_2",
                    "node_type": "classification.plsda",
                    "label": "PLS-DA",
                    "parameters": {"n_components": 2},
                    "position_x": 500,
                    "position_y": 250,
                },
                {
                    "node_id": "model_3",
                    "node_type": "classification.simca",
                    "label": "SIMCA",
                    "parameters": {"n_components": 3},
                    "position_x": 500,
                    "position_y": 350,
                },
                {
                    "node_id": "eval_1",
                    "node_type": "diagnostics.cross_validation",
                    "label": "CV - KNN",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 150,
                },
                {
                    "node_id": "eval_2",
                    "node_type": "diagnostics.cross_validation",
                    "label": "CV - PLS-DA",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 250,
                },
                {
                    "node_id": "eval_3",
                    "node_type": "diagnostics.cross_validation",
                    "label": "CV - SIMCA",
                    "parameters": {"cv_folds": 5},
                    "position_x": 700,
                    "position_y": 350,
                },
            ],
            "edges": [
                {"from_node_id": "data_1", "to_node_id": "preprocess_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_1"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_2"},
                {"from_node_id": "preprocess_1", "to_node_id": "model_3"},
                {"from_node_id": "model_1", "to_node_id": "eval_1"},
                {"from_node_id": "model_2", "to_node_id": "eval_2"},
                {"from_node_id": "model_3", "to_node_id": "eval_3"},
            ],
            "canvas_state": {"zoom": 1.0, "pan_x": 0, "pan_y": 0},
        },
        "is_active": True,
    },
]
